common/models/Communique.php
<?php

namespace common\models;
use yii\helpers\Url;
use Yii;

/**
 * This is the model class for table "communique".
 *
 * @property integer $communique_id
 * @property integer $project_ref_id
 * @property integer $user_ref_id
 * @property string $subject
 * @property string $message
 * @property string $to_email
 * @property string $status
 * @property integer $created_by
 * @property string $created_date
 */
class Communique extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'communique';
    }

    /**
     * @inheritdoc
     */
    public $selectemail;
    public $existing_email;
    public $new_email;
    public $username;
    public $projects;
	public $search_user_ref_id;
	public $search_subject;
	public $search_project_ref_id;
	public $from_date;
	public $to_date;
	public $mailstatus;
    public function rules()
    {
        return [
            [['project_ref_id', 'user_ref_id', 'created_by'], 'integer'],
            [['subject', 'status', 'created_by', 'created_date','message'], 'required'],
           // [['message'],'match', 'pattern' => '/^[a-zA-Z0-9_-]+$/', 'message' => 'Html content is not allowed'],
            [['message', 'status'], 'string'],
            [['created_date','from_date','to_date','mailstatus'], 'safe'],
            [['subject'], 'string', 'max' => 255],
            [['to_email'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'communique_id' => 'Communique ID',
            'project_ref_id' => 'Project Ref ID',
            'user_ref_id' => 'User Ref ID',
            'subject' => 'Subject',
            'message' => 'Message',
            'to_email' => 'To Email',
            'status' => 'Status',
            'created_by' => 'Created By',
            'created_date' => 'Created Date',
        ];
    }
    
    public static function saveMailData($project_ref_id = '', $user_ref_id = '', $subject, $message, $to_email, $status = '', $created_by) {
        $model = new Communique();
        $model->project_ref_id = $project_ref_id;
        $model->user_ref_id = $user_ref_id;
        $model->subject = $subject;
        $model->message = $message;
        $model->to_email = $to_email;
        $model->status = $status;
        $model->created_by = $created_by;
        $model->created_date = date('Y-m-d h:i:s');
        $model->save(false);
    }
}

backend/controllers/CommuniqueController.php
<?php

namespace backend\controllers;
use yii\data\SqlDataProvider;
use common\models\Communique;
use common\models\EmailTemplates;
use yii\web\Controller;
use yii\filters\VerbFilter;
use Yii;

class CommuniqueController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }
    public function beforeAction($action) {
        $this->enableCsrfValidation = false;

        if (\Yii::$app->getUser()->isGuest){
            \Yii::$app->getResponse()->redirect(Yii::$app->request->BaseUrl . '/site/login');
        } else {
            return parent::beforeAction($action);
        }
    }
    
    public function actionIndex()
    {
        $this->layout = '/main';
        $model = new Communique();
        
        $QRY = "SELECT COUNT(*) fROM communique AS c "
                . "LEFT JOIN `user_profile` AS up ON up.user_ref_id = c.user_ref_id "
                . "WHERE c.user_ref_id=" . Yii::$app->user->identity->id;
        $COUNT = Yii::$app->db->createCommand($QRY)->queryScalar();
        
        $SQL = "SELECT c.*, if(c.project_ref_id IS NOT NULL, (select project_title from projects where project_id = c.project_ref_id), '') as projecttitle,  CONCAT(up.fname,' ',up.lname) as fullname from communique AS c "
                . "LEFT JOIN `user_profile` AS up ON up.user_ref_id = c.user_ref_id "
                . "WHERE c.user_ref_id=" . Yii::$app->user->identity->id;
        
        $dataProvider = new SqlDataProvider([
            'sql' => $SQL,
            'totalCount' => $COUNT,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        
        return $this->render('index', [
                'dataProvider' => $dataProvider,
                'model' => $model
            ]);
    }
    
     protected function findModel($id) {
        if (($model = Communique::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    
    public function actionInboxMails()
    {  
	$mysqldateformat = Yii::getAlias('@mysqldateformat');
	$subject = (Yii::$app->getRequest()->getQueryParam('subject')) ? Yii::$app->getRequest()->getQueryParam('subject') : "";
	$user_ref = (Yii::$app->getRequest()->getQueryParam('user_ref')) ? Yii::$app->getRequest()->getQueryParam('user_ref') : "";
	$prj_ref = (Yii::$app->getRequest()->getQueryParam('prj_ref')) ? Yii::$app->getRequest()->getQueryParam('prj_ref') : "";
	$fromDate = (Yii::$app->getRequest()->getQueryParam('from_date')) ? Yii::$app->getRequest()->getQueryParam('from_date') : "";
	$toDate = (Yii::$app->getRequest()->getQueryParam('to_date')) ? Yii::$app->getRequest()->getQueryParam('to_date') : "";
	$mailstatus = (Yii::$app->getRequest()->getQueryParam('mailstatus')) ? Yii::$app->getRequest()->getQueryParam('mailstatus') : "";
	
	$where = '';
        if(  !empty($subject) || !empty($user_ref) || !empty($prj_ref) || !empty($fromDate) || !empty($toDate) || !empty($mailstatus) ) {
            $where .= (!empty($subject)) ? " AND c.subject LIKE '%".$subject."%'" : "";
            $where .= (!empty($user_ref)) ? " AND CONCAT(up.fname, ' ', up.lname) LIKE '%".$user_ref."%'" : "";
            $where .= (!empty($prj_ref)) ? " AND p.project_title LIKE '%".$prj_ref."%'" : "";
            $where .= (!empty($fromDate)) ? ' AND DATE_FORMAT(c.created_date, "%Y-%m-%d") >= "'.date('Y-m-d', strtotime($fromDate) ).'"' : "";
			$where .= (!empty($toDate)) ? ' AND DATE_FORMAT(c.created_date, "%Y-%m-%d") <= "'.date('Y-m-d', strtotime($toDate) ).'"' : "";
			if($mailstatus == 'Read' || $mailstatus == 'Unread'){
				$where .= (!empty($mailstatus)) ? ' AND c.status="'.$mailstatus.'"' : '';
			}
        }
        $model = new Communique();
        $this->layout = '/main';
        $SQL = "SELECT c.*, if(c.project_ref_id IS NOT NULL, (select project_title from projects where project_id = c.project_ref_id), '') as projecttitle,  CONCAT(up.fname,' ',up.lname) as fullname from communique AS c ";
 $QRY = "SELECT COUNT(*) fROM communique AS c "
                . "LEFT JOIN `user_profile` AS up ON up.user_ref_id = c.created_by "
				. "LEFT JOIN `projects` AS p ON p.project_id = c.project_ref_id "
                . "WHERE c.user_ref_id=" . Yii::$app->user->identity->id.$where;
        $COUNT = Yii::$app->db->createCommand($QRY)->queryScalar();
        
        $SQL = "SELECT c.*, DATE_FORMAT(c.created_date, '".$mysqldateformat." %h:%i %p') as createddate, if(c.project_ref_id IS NOT NULL, p.project_title, '') as projecttitle,  CONCAT(up.fname,' ',up.lname) as fullname FROM communique AS c "
                . "LEFT JOIN `user_profile` AS up ON up.user_ref_id = c.created_by "
				. "LEFT JOIN `projects` AS p ON p.project_id = c.project_ref_id "
                . "WHERE c.user_ref_id=" . Yii::$app->user->identity->id.$where." ORDER BY c.communique_id DESC, DATE_FORMAT(c.created_date, '%Y-%m-%d') DESC";
        $dataProvider = new SqlDataProvider([
            'sql' => $SQL,
            'totalCount' => $COUNT,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        return $this->render('inbox-mails', [
                    'dataProvider' => $dataProvider,
                    'count' => $COUNT,
					'model' => $model,
                ]);

    }
    
    public function actionMailView()
    {
         $this->layout = false;
        $mailid = isset($_POST['mailid']) ? $_POST['mailid'] : '';
		$mailtype = isset($_POST['mailtype']) ? $_POST['mailtype'] : '';
        $communique = Communique::find()->where(['communique_id' => $mailid])->one();
        if($mailtype == 'inbox'){
        $communique->status = 'Read';
		$communique->save();
		}
        
        $SQL = "SELECT c.*, CONCAT(up.fname,' ',up.lname) as fullname from communique AS c "
                . "LEFT JOIN `user_profile` AS up ON up.user_ref_id = c.user_ref_id "
                . "WHERE c.communique_id=" . $mailid;
        $mail = Yii::$app->db->createCommand($SQL)->queryAll();
        $maildata = array_shift($mail);
        return $this->renderPartial('mail-view', [
                'maildata' => $maildata
            ]);
    }
    
    public function actionSentMails()
    {
	$mysqldateformat = Yii::getAlias('@mysqldateformat');
        $model = new Communique();$this->layout = '/main';
        $subject = (Yii::$app->getRequest()->getQueryParam('subject')) ? Yii::$app->getRequest()->getQueryParam('subject') : "";
	$user_ref = (Yii::$app->getRequest()->getQueryParam('user_ref')) ? Yii::$app->getRequest()->getQueryParam('user_ref') : "";
	$prj_ref = (Yii::$app->getRequest()->getQueryParam('prj_ref')) ? Yii::$app->getRequest()->getQueryParam('prj_ref') : "";
	$fromDate = (Yii::$app->getRequest()->getQueryParam('from_date')) ? Yii::$app->getRequest()->getQueryParam('from_date') : "";
	$toDate = (Yii::$app->getRequest()->getQueryParam('to_date')) ? Yii::$app->getRequest()->getQueryParam('to_date') : "";
	$where = '';
	
	if(  !empty($subject) || !empty($user_ref) || !empty($prj_ref) || !empty($fromDate) || !empty($toDate) ) {
            $where .= (!empty($subject)) ? " AND c.subject LIKE '%".$subject."%'" : "";
            $where .= (!empty($user_ref)) ? " AND CONCAT(up.fname, ' ', up.lname) LIKE '%".$user_ref."%'" : "";
            $where .= (!empty($prj_ref)) ? " AND p.project_title LIKE '%".$prj_ref."%'" : "";
            $where .= (!empty($fromDate)) ? ' AND DATE_FORMAT(c.created_date, "%Y-%m-%d") >= "'.date('Y-m-d', strtotime($fromDate) ).'"' : "";
			$where .= (!empty($toDate)) ? ' AND DATE_FORMAT(c.created_date, "%Y-%m-%d") <= "'.date('Y-m-d', strtotime($toDate) ).'"' : "";
        }
        $QRY = "SELECT COUNT(*) fROM communique AS c "
                . "LEFT JOIN `user_profile` AS up ON up.user_ref_id = c.user_ref_id "
				. "LEFT JOIN `projects` AS p ON p.project_id = c.project_ref_id "
                . "WHERE c.created_by=" . Yii::$app->user->identity->id.$where;
        $COUNT = Yii::$app->db->createCommand($QRY)->queryScalar();
        
$SQL = "SELECT c.*, DATE_FORMAT(c.created_date, '".$mysqldateformat." %h:%i %p') as created_date, if(c.project_ref_id IS NOT NULL, p.project_title, '') as projecttitle,  CONCAT(up.fname,' ',up.lname) as fullname from communique AS c "
                . "LEFT JOIN `user_profile` AS up ON up.user_ref_id = c.user_ref_id "
				. "LEFT JOIN `projects` AS p ON p.project_id = c.project_ref_id "
                . "WHERE c.created_by=" . Yii::$app->user->identity->id.$where." ORDER BY c.communique_id DESC, DATE_FORMAT(c.created_date, '%Y-%m-%d') DESC";
        
        $dataProvider = new SqlDataProvider([
            'sql' => $SQL,
            'totalCount' => $COUNT,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
      // print_r($dataProvider); exit;
        return $this->render('sent-mails', [
                    'dataProvider' => $dataProvider,
                'model' => $model,
                'count' => $COUNT
                ]);

    }
    
    public function actionNewMessage()
    {
        $this->layout = '/main';
        $this->view->title = 'New message';
        $communique = new Communique();
        $sql = "SELECT CONCAT(fname, ' ', lname, ' , ', user_type, ' , ', email) as value, id as id  FROM `user`  u 
                LEFT JOIN project_co_owners pc ON pc.user_ref_id = u.id
                JOIN user_profile up ON u.id = up.user_ref_id
                JOIN user_type ut ON u.user_type_ref_id = ut.user_type_id 
                GROUP BY u.id ORDER BY email";
        
        $users = Yii::$app->db->createCommand($sql)->queryAll();
        

frontend/views/communique/index.php
<?php
    use yii\helpers\Url;
use yii\widgets\DetailView;
$this->registerJsFile(Yii::getAlias('@web/themes/custom/plugins/owl-carousel/assets/js/jquery-1.9.1.min.js'),['position' => \yii\web\View::POS_HEAD]);
$this->registerJsFile(Yii::getAlias('@web/themes/metronic/assets/global/plugins/ckeditor/ckeditor.js'),['position' => \yii\web\View::POS_HEAD]);
$this->registerJsFile(Yii::getAlias('@web/themes/metronic/assets/global/plugins/chosen/chosen.jquery.js'),['position' => \yii\web\View::POS_HEAD]);
$this->registerCssFile(Yii::getAlias('@web/themes/metronic/assets/global/plugins/chosen/chosen.css'),['position' => \yii\web\View::POS_HEAD]);
?>
<div class="mail-container">
<div class="mail-communique">
<div id="inbox"></div>
<div id="sent"></div>
</div>
</div>
<script>
    $(this).scrollTop(0);
    var mailviewurl = '<?php echo Yii::$app->urlManager->createAbsoluteUrl('communique/mail-view'); ?>';
    var inboxurl = '<?php echo Yii::$app->urlManager->createAbsoluteUrl('communique/inbox-mails'); ?>';
    var senturl = '<?php echo Yii::$app->urlManager->createAbsoluteUrl('communique/sent-mails'); ?>';
    var newmsgurl = '<?php echo Yii::$app->urlManager->createAbsoluteUrl('communique/new-message'); ?>';
    
    function openmailbox(mailid,tbox){
        $(this).scrollTop(0);
        if(tbox=='inbox'){
        location.hash = 'inbox/'+mailid;
    }else if(tbox=='sent'){
        location.hash = 'sent/'+mailid;
    }
    }
    function opencontent(mailid){
        $(this).scrollTop(0);
           var mailid = mailid;
            $('#inbox').empty();
            $('#sent').empty();
            $.ajax({
                    url: mailviewurl,
                    type: "post",
                    dataType: "html",
                    data: {mailid:mailid},
                    success: function (data) {
                        $('#inbox').html(data);
                        
                    }
                });
       }
       function inboxmails(){
           $(this).scrollTop(0);
           $('#inbox').empty();
           $('#sent').empty();
          // $('#newmessage').empty();
           $.ajax({
                    url: inboxurl,
                    type: "post",
                    dataType: "html",
                    success: function (data) {
                        $('#inbox').html(data);
                        
                    }
                });
            }
       function sentmailsbox(){
           $(this).scrollTop(0);
           $('#inbox').empty();
           $('#sent').empty();
           //$('#newmessage').empty();
           $.ajax({
                    url: senturl,
                    type: "post",
                    dataType: "html",
                    success: function (data) {
                        $('#sent').html(data);
                        
                    }
                });
           
       }
       function newmessage(){
           $(this).scrollTop(0);
           $('#inbox').empty();
           $('#sent').empty();
           //$('#newmessage').empty();
           $.ajax({
                    url: newmsgurl,
                    type: "post",
                    success: function (data) {
                        $('#newmessage').append(data);
                        
                    }
                });
           
       }
     
    $(function(){ 
        changecontent();
    $(window).bind('hashchange', function(e) {
        $(this).scrollTop(0);
    var what_to_do = window.location.hash;    
   if (what_to_do=="#inbox"){
       inboxmails();
   }else if(what_to_do=="#sent"){
       sentmailsbox();
   }else if(what_to_do=="#new-message"){
       newmessage();
   }
   if (what_to_do.indexOf("sent/") >= 0){
            var msgid = what_to_do.split('sent/')[1];
            opencontent(msgid);
        }else if (what_to_do.indexOf("inbox/") >= 0){
            var msgid = what_to_do.split('inbox/')[1];
            opencontent(msgid);
        }
    });
});
function changecontent(){
    $(this).scrollTop(0);
    var what_to_do = window.location.hash;    
   if (what_to_do=="#inbox"){
       inboxmails();
   }else if(what_to_do=="#sent"){
       sentmailsbox();
   }else if(what_to_do=="#new-message"){
       newmessage();
   }
   if (what_to_do.indexOf("sent/") >= 0){
            var msgid = what_to_do.split('sent/')[1];
            opencontent(msgid);
        }else if (what_to_do.indexOf("inbox/") >= 0){
            var msgid = what_to_do.split('inbox/')[1];
            opencontent(msgid);
        }
}
    
    </script>

<style>
    .unread{
     font-weight:bold;   
}
    </style>

frontend/views/communique/mail-view.php
<?php
$phpdateformat = Yii::getAlias('@phpdateformat');
echo "<div class='subjectcontent'><div class='mailsubject'>".$maildata['subject']."</div><div class='mailtime'>".date($phpdateformat.' h:i:s A', strtotime($maildata['created_date']))."</div></div>";
echo '<br>';
echo "<div class='mailbody table-responsive'>".$maildata['message']."</div>";

                ?>

frontend/views/communique/sent-mails.php
<?php
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\helpers\Html;
use yii\widgets\Pjax;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;
$this->title = 'Sent';
$dateformat = Yii::getAlias('@phpdatepickerformat');		
$phpdateformat = Yii::getAlias('@phpdateformat');
?>

<h1 class="box-title"><?php echo Html::encode($this->title) ?></h1>
<div class="searchBox row">
<div class="pull-left col-sm-11 rgt-padding0 colsm11-12">
    <?php $form = ActiveForm::begin(); ?>
	 <?php //echo $form->field($model, 'search_user_ref_id', ['options' => ['class' => 'clsDropdown col-sm-2 col-xs-12 communiqueInbox']])->textInput(array('placeholder' => 'Username'))->label(false) ?>
    <?php echo $form->field($model, 'search_subject', ['options' => ['class' => 'clsDropdown col-sm-2 col-xs-12 communiqueInbox']])->textInput(array('placeholder' => 'Subject'))->label(false) ?>
   
	<?php echo $form->field($model, 'search_project_ref_id', ['options' => ['class' => 'clsDropdown col-sm-2 col-xs-12 communiqueInbox']])->textInput(array('placeholder' => 'Reference to'))->label(false) ?>
	
    <div class="col-sm-2 col-xs-12 custom-calendar">
        <?php echo $form->field($model, 'from_date')->widget(DatePicker::classname(), [
                        'value'  => @$value, 'dateFormat' => $dateformat, 'value' => date('Y-m-d'), 'options' => ['class' => 'clsDropdown col-sm-3 col-xs-12'],
                        'clientOptions' => [
                            'changeMonth' => true,
                            'yearRange' => "2015:(date('Y')+5)",
                            'changeYear' => true,
                            'showOn' => 'button',
                            'buttonImage' => 'images/calendar.gif',
                            'buttonImageOnly' => true,
                            'buttonText' => 'Select date',
                            'buttonImage' => Yii::$app->request->BaseUrl.'/images/calendar.gif',                     
                        ],
                ])->textInput(['readonly' => true])->label('');
        ?>
    </div>
	<div class="col-sm-2 col-xs-12 custom-calendar">
        <?php echo $form->field($model, 'to_date')->widget(DatePicker::classname(), [
                        'value'  => @$value, 'dateFormat' => $dateformat, 'value' => date('Y-m-d'), 'options' => ['class' => 'clsDropdown col-sm-3 col-xs-12'],
                        'clientOptions' => [
                            'changeMonth' => true,
                            'yearRange' => "2015:(date('Y')+5)",
                            'changeYear' => true,
                            'showOn' => 'button',
                            'buttonImage' => 'images/calendar.gif',
                            'buttonImageOnly' => true,
                            'buttonText' => 'Select date',
                            'buttonImage' => Yii::$app->request->BaseUrl.'/images/calendar.gif',          
                        ],
                ])->textInput(['readonly' => true])->label('');
        ?>
    </div>
    </div>
    
    <div class="pull-right col-sm-1 btn-sbrt">
    <div class="col-sm-6 col-xs-12 searchBtn group-btn-search" style="padding:0;">
        <?php echo Html::submitButton('<i class="fa fa-search ic-srch"></i>' , ['class' => 'btn btn-success', 'id' => 'btnInboxSearch']) ?>
        <input type="hidden" value="<?php echo Yii::$app->request->BaseUrl; ?>/communique/sent-mails" id="searchUrl_initiated">
    </div>
    <div class="col-sm-6 col-xs-12 searchBtn group-btn-search" style="padding:0;">
        <?php echo Html::submitButton('<i class="fa fa-refresh"></i>' , ['class' => 'btn btn-success res-bnt', 'id' => 'btnCommuniqueReset']) ?>
    </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>
<div class="sentmails send-infomail" id="sent">
    <?php Pjax::begin([
                'id' => 'pjax-list-initiated',
                'timeout' => false,
                'enablePushState'=>false
            ]);
			if($count){
                    echo yii\grid\GridView::widget([
                        'dataProvider' => $dataProvider,
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],
                             [ 
                                'attribute' => 'fullname',
                                'label' => 'Username',
                            ],
                            'subject',
                            [ 
                                'attribute' => 'projecttitle',
                                'label' => 'Reference to',
                            ],
                            [ 
                                'attribute' => 'created_date',
                                'label' => 'Date',
                                'format' =>  ['date', 'php:'.$phpdateformat.' h:i:s A'],
                            ],
                        ],
                        
                        'rowOptions' => function($model) {
                            return ['class' => 'mailinbox', 'mailid' => $model['communique_id'],'onclick' => "javascript:openmailbox(".$model['communique_id'].",'sent')"];
                    }
                    ]);
}else{
        echo "<div class='nodata'>No sent mails</div>";
    }
	Pjax::end();
                ?>
</div>
<script>
    $('.sentmails table thead tr').addClass('trclass');
	$("#communique-from_date").attr("placeholder", "From Date");
  $("#communique-to_date").attr("placeholder", "To Date");
    var mailviewurl = '<?php echo Yii::$app->urlManager->createAbsoluteUrl('communique/mail-view'); ?>';
    
    function openmailbox(mailid,tbox){
        if(tbox=='inbox'){
        location.hash = 'inbox/'+mailid;
    }else if(tbox=='sent'){
        location.hash = 'sent/'+mailid;
    }
    }
    function opencontent(mailid){
           var mailid = mailid;
            $('#sent').empty();
            $.ajax({
                    url: mailviewurl,
                    type: "post",
                    dataType: "html",
                    data: {mailid:mailid},
                    success: function (data) {
                        $('#sent').html(data);
                        
                    }
                });
       }
       
     
    $(function(){ 
        var redirecturl ='<?php echo Yii::$app->urlManager->createAbsoluteUrl('communique/sent-mails'); ?>';
        var what_to_do = document.location.hash;    
   if (what_to_do.indexOf("sent/") >= 0){
            var msgid = what_to_do.split('sent/')[1];
            opencontent(msgid);
        }else if (what_to_do.indexOf("inbox/") >= 0){
            var msgid = what_to_do.split('inbox/')[1];
            opencontent(msgid);
        }
    window.onhashchange = function() {   
       var what_to_do = document.location.hash;    
   if (what_to_do.indexOf("sent/") >= 0){
            var msgid = what_to_do.split('sent/')[1];
            opencontent(msgid);
        }else if (what_to_do.indexOf("inbox/") >= 0){
            var msgid = what_to_do.split('inbox/')[1];
            opencontent(msgid);
        }else if(what_to_do == ''){
            window.location.reload(redirecturl);
        }
    }
});


$("#communique-from_date").attr("placeholder", "From Date");
  $("#communique-to_date").attr("placeholder", "To Date");
$('#btnInboxSearch').on('click', function (e) {
var pjaxContainer_initiated = 'pjax-list-initiated' ;
			var searchUrl_initiated = $('#searchUrl_initiated').val();
            var communique_subject = $('#communique-search_subject').val();
            var communique_user_ref_id = $('.communiqueInbox #communique-search_user_ref_id').val();
            var communique_prj_ref_id = $('.communiqueInbox #communique-search_project_ref_id').val();
            var communique_from_date = $('#communique-from_date').val();
			var communique_to_date = $('#communique-to_date').val();
			var mailstatus = $('#communique-mailstatus').val();
            var pjaxReloadURL_initiated = searchUrl_initiated+'?subject='+communique_subject+'&user_ref='+communique_user_ref_id+'&prj_ref='+communique_prj_ref_id+'&from_date='+communique_from_date+'&to_date='+communique_to_date+'&mailstatus='+mailstatus;
			console.log(pjaxReloadURL_initiated);
             $.ajax({
                url:   searchUrl_initiated,
                type: 'get',
                data: {'subject': communique_subject, 'user': communique_user_ref_id, 'project': communique_prj_ref_id, 'from_date': communique_from_date, 'to_date': communique_to_date, 'mailstatus': mailstatus},
                success: function(data){
                    if(data){ 
                        //$.pjax.reload({url: pjaxReloadURL, container: '#' + $.trim(pjaxContainer, )});
                        $.pjax.reload({url: pjaxReloadURL_initiated, container: '#' + $.trim(pjaxContainer_initiated), async:false, reload: true,});
                        return false;
                    }
                },
                error: function (xhr, status, error) {
                   alert('There was an error with your request.' + xhr.responseText);
                 }
             }); 
             return false;
        });
		
		$('#btnCommuniqueReset').on('click', function (e) {
            var searchUrl_initiated = $('#searchUrl_initiated').val();
            var pjaxContainer = 'pjax-list-initiated' ;
            var pjaxReloadURL = searchUrl_initiated;

             $.ajax({
                url:   searchUrl_initiated,
                type: 'get',
                //data: {'title': projectTitle, 'cat': projectCategory, 'type': projectType, 'status': projectStatus, 'from': from, 'to': to},
                success: function(data){
                    if(data){ 
							$('#communique-search_subject').val('');
							$('.communiqueInbox #communique-search_user_ref_id').val('');
							$('.communiqueInbox #communique-search_project_ref_id').val('');
							$('#communique-from_date').datepicker('setDate', null);
							$('#communique-to_date').datepicker('setDate', null);
							$('#communique-mailstatus').val('');
                        //$.pjax.reload({url: pjaxReloadURL, container: '#' + $.trim(pjaxContainer, )});
                        $.pjax.reload({url: pjaxReloadURL, container: '#' + $.trim(pjaxContainer), async:false});
                        return false;
                    }
                },
                error: function (xhr, status, error) {
                   alert('There was an error with your request.' + xhr.responseText);
                 }
             }); 
             return false;
        });
</script>